apiVersion: apps/v1
kind: Deployment
metadata:
  name: beatbuddy-backend
  namespace: beatbuddy

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  minReadySeconds: 10

  selector:
    matchLabels:
      app: beatbuddy-backend

  template:
    metadata:
      labels:
        app: beatbuddy-backend

    spec:
      containers:
        - name: beatbuddy-backend
          image: yeaxyzi/beatbuddy-backend:IMAGE_TAG
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "live"
          envFrom:
            - secretRef:
                name: beatbuddy-secret
