apiVersion: v1
kind: Secret
metadata:
  name: beatbuddy-secret
  namespace: default
type: Opaque
stringData:
  SPRING_MAIL_USERNAME: "${SPRING_MAIL_USERNAME}"
  SPRING_MAIL_PASSWORD: "${SPRING_MAIL_PASSWORD}"
  JWT_ISSUER: "${JWT_ISSUER}"
  JWT_SECRET: "${JWT_SECRET}"
  SPOTIFY_CLIENT_ID: "${SPOTIFY_CLIENT_ID}"
  SPOTIFY_CLIENT_SECRET: "${SPOTIFY_CLIENT_SECRET}"
  RAPIDAPI_KEY: "${RAPIDAPI_KEY}"