apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beatbuddy-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: beatbuddy-backend
                port:
                  number: 8080
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: beatbuddy-backend
                port:
                  number: 8080
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: beatbuddy-backend
                port:
                  number: 8080
          - path: /v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: beatbuddy-backend
                port:
                  number: 8080
          - path: /images
            pathType: Prefix
            backend:
              service:
                name: beatbuddy-backend
                port:
                  number: 8080
          - path: /default-profile.jpg
            pathType: Exact
            backend:
              service:
                name: beatbuddy-backend
                port:
                  number: 8080
          - path: /default-group.jpg
            pathType: Exact
            backend:
              service:
                name: beatbuddy-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: beatbuddy-frontend
                port:
                  number: 80
