apiVersion: apps/v1
kind: Deployment
metadata:
  name: beatbuddy-frontend
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: beatbuddy-frontend
  template:
    metadata:
      labels:
        app: beatbuddy-frontend
    spec:
      containers:
        - name: beatbuddy-frontend
          image: yeaxyzi/beatbuddy-frontend:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 80
