apiVersion: v1
kind: Service
metadata:
  name: beatbuddy-backend
  namespace: default
spec:
  selector:
    app: beatbuddy-backend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080