server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/beatbuddy
    username: beyond
    password: beyond
  data:
    redis:
      host: redis
      username: default
      password: beyond
      port: 6379

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
    allowed-origin-patterns: ${APP_CORS_ALLOWED_ORIGIN_PATTERNS:*.trycloudflare.com}
